import java.io.PrintWriter;

public class UiRenderer {
    private UiRenderer() {
    }

    public static void printDocumentStart(PrintWriter out, String title) {
        out.println("<!DOCTYPE html>");
        out.println("<html lang='pt-BR'>");
        out.println("<head>");
        out.println("<meta charset='UTF-8'>");
        out.println("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
        out.println("<title>" + escape(title) + "</title>");
        out.println("<style>");
        out.println(":root {");
        out.println("  --bg: #f4efe7;");
        out.println("  --bg-accent: #efe2d0;");
        out.println("  --panel: rgba(255, 250, 243, 0.9);");
        out.println("  --panel-strong: #fffdf9;");
        out.println("  --line: rgba(120, 92, 59, 0.16);");
        out.println("  --text: #2c221b;");
        out.println("  --muted: #6f6255;");
        out.println("  --brand: #c96f3b;");
        out.println("  --brand-deep: #9f4f25;");
        out.println("  --brand-soft: #f6d7bd;");
        out.println("  --ok: #1f7a5a;");
        out.println("  --danger: #b7452f;");
        out.println("  --shadow: 0 24px 80px rgba(78, 52, 31, 0.14);");
        out.println("}");
        out.println("* { box-sizing: border-box; }");
        out.println("html { scroll-behavior: smooth; }");
        out.println("body {");
        out.println("  margin: 0;");
        out.println("  min-height: 100vh;");
        out.println("  font-family: 'Segoe UI', 'Trebuchet MS', sans-serif;");
        out.println("  color: var(--text);");
        out.println("  background:");
        out.println("    radial-gradient(circle at top left, rgba(201, 111, 59, 0.18), transparent 28%),");
        out.println("    radial-gradient(circle at right 20%, rgba(85, 135, 112, 0.18), transparent 24%),");
        out.println("    linear-gradient(180deg, #fcf8f2 0%, var(--bg) 52%, #efe4d5 100%);");
        out.println("}");
        out.println("body::before,");
        out.println("body::after {");
        out.println("  content: '';");
        out.println("  position: fixed;");
        out.println("  inset: auto;");
        out.println("  border-radius: 999px;");
        out.println("  pointer-events: none;");
        out.println("  filter: blur(8px);");
        out.println("  opacity: 0.75;");
        out.println("}");
        out.println("body::before {");
        out.println("  width: 18rem;");
        out.println("  height: 18rem;");
        out.println("  top: -4rem;");
        out.println("  right: -4rem;");
        out.println("  background: rgba(201, 111, 59, 0.16);");
        out.println("}");
        out.println("body::after {");
        out.println("  width: 20rem;");
        out.println("  height: 20rem;");
        out.println("  bottom: -7rem;");
        out.println("  left: -4rem;");
        out.println("  background: rgba(72, 124, 112, 0.14);");
        out.println("}");
        out.println("a { color: inherit; text-decoration: none; }");
        out.println(".page {");
        out.println("  position: relative;");
        out.println("  width: min(1120px, calc(100% - 32px));");
        out.println("  margin: 0 auto;");
        out.println("  padding: 32px 0 56px;");
        out.println("}");
        out.println(".hero {");
        out.println("  display: grid;");
        out.println("  grid-template-columns: 1.15fr 0.85fr;");
        out.println("  gap: 24px;");
        out.println("  align-items: stretch;");
        out.println("  margin-bottom: 26px;");
        out.println("}");
        out.println(".hero-card,");
        out.println(".panel,");
        out.println(".stat-card,");
        out.println(".message-card,");
        out.println(".table-wrap {");
        out.println("  background: var(--panel);");
        out.println("  border: 1px solid var(--line);");
        out.println("  backdrop-filter: blur(18px);");
        out.println("  box-shadow: var(--shadow);");
        out.println("}");
        out.println(".hero-card {");
        out.println("  border-radius: 32px;");
        out.println("  padding: 34px;");
        out.println("  position: relative;");
        out.println("  overflow: hidden;");
        out.println("}");
        out.println(".hero-card::after {");
        out.println("  content: '';");
        out.println("  position: absolute;");
        out.println("  width: 220px;");
        out.println("  height: 220px;");
        out.println("  right: -60px;");
        out.println("  top: -80px;");
        out.println("  background: radial-gradient(circle, rgba(201, 111, 59, 0.26) 0%, rgba(201, 111, 59, 0) 68%);");
        out.println("}");
        out.println(".eyebrow {");
        out.println("  display: inline-flex;");
        out.println("  align-items: center;");
        out.println("  gap: 8px;");
        out.println("  padding: 8px 14px;");
        out.println("  border-radius: 999px;");
        out.println("  background: rgba(255, 255, 255, 0.62);");
        out.println("  border: 1px solid rgba(120, 92, 59, 0.14);");
        out.println("  font-size: 12px;");
        out.println("  letter-spacing: 0.12em;");
        out.println("  text-transform: uppercase;");
        out.println("  color: var(--brand-deep);");
        out.println("}");
        out.println("h1, h2, h3 {");
        out.println("  margin: 0;");
        out.println("  font-family: Georgia, 'Times New Roman', serif;");
        out.println("  letter-spacing: -0.02em;");
        out.println("}");
        out.println("h1 {");
        out.println("  margin-top: 18px;");
        out.println("  font-size: clamp(2.2rem, 5vw, 4rem);");
        out.println("  line-height: 0.95;");
        out.println("}");
        out.println(".hero p,");
        out.println(".panel p,");
        out.println(".message-card p {");
        out.println("  color: var(--muted);");
        out.println("  line-height: 1.7;");
        out.println("}");
        out.println(".hero-copy {");
        out.println("  max-width: 42rem;");
        out.println("  margin: 16px 0 22px;");
        out.println("}");
        out.println(".actions,");
        out.println(".secondary-actions {");
        out.println("  display: flex;");
        out.println("  flex-wrap: wrap;");
        out.println("  gap: 12px;");
        out.println("}");
        out.println(".btn {");
        out.println("  appearance: none;");
        out.println("  border: 0;");
        out.println("  border-radius: 16px;");
        out.println("  padding: 14px 20px;");
        out.println("  font-size: 0.98rem;");
        out.println("  font-weight: 700;");
        out.println("  cursor: pointer;");
        out.println("  transition: transform 0.18s ease, box-shadow 0.18s ease, background 0.18s ease;");
        out.println("  display: inline-flex;");
        out.println("  align-items: center;");
        out.println("  justify-content: center;");
        out.println("  gap: 10px;");
        out.println("}");
        out.println(".btn:hover { transform: translateY(-2px); }");
        out.println(".btn-primary {");
        out.println("  color: #fffaf4;");
        out.println("  background: linear-gradient(135deg, var(--brand) 0%, var(--brand-deep) 100%);");
        out.println("  box-shadow: 0 16px 28px rgba(159, 79, 37, 0.26);");
        out.println("}");
        out.println(".btn-secondary {");
        out.println("  color: var(--text);");
        out.println("  background: rgba(255, 255, 255, 0.76);");
        out.println("  border: 1px solid rgba(120, 92, 59, 0.14);");
        out.println("}");
        out.println(".btn-ghost {");
        out.println("  color: var(--brand-deep);");
        out.println("  background: rgba(201, 111, 59, 0.08);");
        out.println("  border: 1px solid rgba(201, 111, 59, 0.18);");
        out.println("}");
        out.println(".hero-aside {");
        out.println("  display: grid;");
        out.println("  gap: 18px;");
        out.println("}");
        out.println(".stat-card {");
        out.println("  border-radius: 28px;");
        out.println("  padding: 24px;");
        out.println("}");
        out.println(".stat-label {");
        out.println("  font-size: 12px;");
        out.println("  letter-spacing: 0.12em;");
        out.println("  text-transform: uppercase;");
        out.println("  color: var(--muted);");
        out.println("}");
        out.println(".stat-value {");
        out.println("  margin-top: 14px;");
        out.println("  font-size: clamp(2rem, 4vw, 3rem);");
        out.println("  font-family: Georgia, 'Times New Roman', serif;");
        out.println("}");
        out.println(".stat-note {");
        out.println("  margin-top: 12px;");
        out.println("  color: var(--muted);");
        out.println("  line-height: 1.6;");
        out.println("}");
        out.println(".panel {");
        out.println("  border-radius: 28px;");
        out.println("  padding: 28px;");
        out.println("}");
        out.println(".panel-header {");
        out.println("  display: flex;");
        out.println("  justify-content: space-between;");
        out.println("  gap: 16px;");
        out.println("  align-items: flex-start;");
        out.println("  margin-bottom: 24px;");
        out.println("}");
        out.println(".panel-title {");
        out.println("  font-size: clamp(1.6rem, 3vw, 2.4rem);");
        out.println("}");
        out.println(".grid-2 {");
        out.println("  display: grid;");
        out.println("  grid-template-columns: repeat(2, minmax(0, 1fr));");
        out.println("  gap: 18px;");
        out.println("}");
        out.println(".field {");
        out.println("  display: grid;");
        out.println("  gap: 8px;");
        out.println("}");
        out.println(".field.full { grid-column: 1 / -1; }");
        out.println("label {");
        out.println("  font-size: 0.92rem;");
        out.println("  font-weight: 700;");
        out.println("}");
        out.println("input,");
        out.println("select {");
        out.println("  width: 100%;");
        out.println("  border-radius: 16px;");
        out.println("  border: 1px solid rgba(120, 92, 59, 0.18);");
        out.println("  background: rgba(255, 255, 255, 0.82);");
        out.println("  padding: 15px 16px;");
        out.println("  font-size: 1rem;");
        out.println("  color: var(--text);");
        out.println("  outline: none;");
        out.println("  transition: border-color 0.18s ease, box-shadow 0.18s ease, transform 0.18s ease;");
        out.println("}");
        out.println("input:focus,");
        out.println("select:focus {");
        out.println("  border-color: rgba(201, 111, 59, 0.62);");
        out.println("  box-shadow: 0 0 0 4px rgba(201, 111, 59, 0.14);");
        out.println("  transform: translateY(-1px);");
        out.println("}");
        out.println(".hint {");
        out.println("  font-size: 0.92rem;");
        out.println("  color: var(--muted);");
        out.println("}");
        out.println(".form-actions {");
        out.println("  margin-top: 24px;");
        out.println("  display: flex;");
        out.println("  flex-wrap: wrap;");
        out.println("  gap: 12px;");
        out.println("}");
        out.println(".table-wrap {");
        out.println("  border-radius: 28px;");
        out.println("  overflow: hidden;");
        out.println("}");
        out.println("table {");
        out.println("  width: 100%;");
        out.println("  border-collapse: collapse;");
        out.println("}");
        out.println("thead {");
        out.println("  background: rgba(201, 111, 59, 0.1);");
        out.println("}");
        out.println("th,");
        out.println("td {");
        out.println("  padding: 18px 16px;");
        out.println("  text-align: left;");
        out.println("  border-bottom: 1px solid rgba(120, 92, 59, 0.1);");
        out.println("}");
        out.println("tbody tr:hover {");
        out.println("  background: rgba(255, 255, 255, 0.45);");
        out.println("}");
        out.println(".pill {");
        out.println("  display: inline-flex;");
        out.println("  align-items: center;");
        out.println("  border-radius: 999px;");
        out.println("  padding: 8px 12px;");
        out.println("  background: rgba(201, 111, 59, 0.09);");
        out.println("  color: var(--brand-deep);");
        out.println("  font-size: 0.88rem;");
        out.println("  font-weight: 700;");
        out.println("}");
        out.println(".empty-state {");
        out.println("  padding: 46px 24px;");
        out.println("  text-align: center;");
        out.println("}");
        out.println(".message-layout {");
        out.println("  min-height: calc(100vh - 88px);");
        out.println("  display: grid;");
        out.println("  place-items: center;");
        out.println("}");
        out.println(".message-card {");
        out.println("  width: min(760px, 100%);");
        out.println("  border-radius: 32px;");
        out.println("  padding: 36px;");
        out.println("  text-align: center;");
        out.println("}");
        out.println(".status-icon {");
        out.println("  width: 74px;");
        out.println("  height: 74px;");
        out.println("  border-radius: 24px;");
        out.println("  display: inline-grid;");
        out.println("  place-items: center;");
        out.println("  margin-bottom: 18px;");
        out.println("  font-size: 2rem;");
        out.println("  font-weight: 700;");
        out.println("}");
        out.println(".status-success { background: rgba(31, 122, 90, 0.14); color: var(--ok); }");
        out.println(".status-error { background: rgba(183, 69, 47, 0.14); color: var(--danger); }");
        out.println(".status-info { background: rgba(201, 111, 59, 0.14); color: var(--brand-deep); }");
        out.println(".toast {");
        out.println("  display: inline-flex;");
        out.println("  align-items: center;");
        out.println("  gap: 10px;");
        out.println("  margin-top: 18px;");
        out.println("  padding: 10px 14px;");
        out.println("  border-radius: 999px;");
        out.println("  font-size: 0.92rem;");
        out.println("  background: rgba(255, 255, 255, 0.68);");
        out.println("  border: 1px solid rgba(120, 92, 59, 0.12);");
        out.println("}");
        out.println(".footer {");
        out.println("  margin-top: 26px;");
        out.println("  padding: 0 8px;");
        out.println("  text-align: center;");
        out.println("  color: var(--muted);");
        out.println("  font-size: 0.92rem;");
        out.println("}");
        out.println("@media (max-width: 860px) {");
        out.println("  .hero,");
        out.println("  .grid-2 {");
        out.println("    grid-template-columns: 1fr;");
        out.println("  }");
        out.println("  .page {");
        out.println("    width: min(100% - 20px, 1120px);");
        out.println("    padding-top: 20px;");
        out.println("  }");
        out.println("  .hero-card,");
        out.println("  .panel,");
        out.println("  .message-card,");
        out.println("  .stat-card {");
        out.println("    border-radius: 24px;");
        out.println("    padding: 24px;");
        out.println("  }");
        out.println("  th,");
        out.println("  td {");
        out.println("    padding: 14px 12px;");
        out.println("  }");
        out.println("}");
        out.println("@media (max-width: 640px) {");
        out.println("  .actions,");
        out.println("  .form-actions,");
        out.println("  .secondary-actions {");
        out.println("    flex-direction: column;");
        out.println("  }");
        out.println("  .btn {");
        out.println("    width: 100%;");
        out.println("  }");
        out.println("  .table-wrap {");
        out.println("    overflow-x: auto;");
        out.println("  }");
        out.println("  table {");
        out.println("    min-width: 680px;");
        out.println("  }");
        out.println("}");
        out.println("</style>");
        out.println("</head>");
        out.println("<body>");
    }

    public static void printFooter(PrintWriter out) {
        out.println("<div class='footer'>Projeto realizado por Matheus Correia de Franca e Davi Leite Coelho para a materia de Sistemas Web 1.</div>");
        out.println("</body></html>");
    }

    public static String escape(String value) {
        if (value == null) {
            return "";
        }

        return value
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;");
    }
}
